#see https://alacritty.org/config-alacritty.html
import = [
   "~/.config/alacritty/themes/themes/nord.toml" 
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "OnlyLeft"

[font]
normal.family = "Hack Nerd Font Mono"
size = 17
