format = """
[  ](bg:#E6E6E6 fg:#090c0c)\
[](bg:#973D19 fg:#E6E6E6)\
$directory\
[](fg:#973D19 bg:#394260)\
$git_branch\
$git_status\
[](fg:#2b676b bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$helm\
[](fg:#212736 bg:#1d2230)\
[](fg:#212736 bg:#1d2230)\
[ ](fg:#1d2230)\
\n$character"""

command_timeout=1000

[directory]
style = "fg:#e3e5e5 bg:#973D19"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#E6E6E6 bg:#2b676b)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#E6E6E6 bg:#2b676b)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#973D19 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#973D19 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#973D19 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#973D19 bg:#212736)]($style)'

[helm]
symbol = '⎈ '
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#973D19 bg:#212736)]($style)'

[terraform]
symbol = "💠"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#973D19 bg:#212736)]($style)'

[docker_context]
symbol = "🐳 "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#973D19 bg:#212736)]($style)'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
