#!/usr/bin/env bash

# +---------+
# | System  |  
# +---------+

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'

alias bigf='find / -xdev -type f -size +1G' #display big files > 1G
alias bigd='find / -xdev -type d -size +1G' #display big directories > 1G

# +-----+
# | Zsh |  
# +-----+

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index #directory stack

# +----+
# | ls |  
# +----+

alias ls='ls -G'
alias ll='ls -lahF'
alias lls='ls -lahFtr'

# +------+
# | grep |  
# +------+

alias grep='grep --color=auto'

# +----+
# | cp |  
# +----+

alias cp='cp -iv'
alias mv='=mv -iv'
alias rm='rm -i'

# +-----+
# | git |  
# +-----+

alias gs='git status'
alias gss='git status -s'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl'git log'
alias gr='git remote'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias gclean="git branch --merged | grep -v '\\*\\|master\\|main\\|develop' | xargs -n 1 git branch -d" # Delete local branches merged with master 
